name: iOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: xcode
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        uses: mxcl/xcodebuild@v1
        with:
          # A semantic version range, eg. ^10, ~10.3 or 10.3.1
          # Leave unset for the image‑default.
          xcode: 14.0
          
          # A semantic version range, eg. ^5, ~5.4 or 5.4.1
          swift: 5.5
          
          # Either `iOS`, `tvOS`, `macOS`, `watchOS` or (more rarely)  `mac-catalyst`
          # Leave unset and `xcodebuild` decides itself.
          platform: iOS
          
          # The most common actions are `test`, `build`.
          # See the `xcodebuild` manual for available actions.
          # Specifying `none` skips the explicit `xcodebuild` step allowing you
          # to use this (GitHub) Action solely for selecting an Xcode version.
          # Specifying `''`, `null` or `~` will cause xcodebuild to behave as it
          # does without an action specified (usually `build`)
          action: build         
          
          # Enables code coverage
          code-coverage: false
          
          # A Base64-encoded certificate to be installed to the macOS Keychain for
          # code signing. It is removed from the keychain in the post action. This
          # certificate should correspond to the `CODE_SIGN_IDENTITY` specified in
          # your project or to the `code-sign-identity` input. Pass this in as a
          # GitHub Encrypted Secret. Requires macOS and
          # `code-sign-certificate-passphrase`.
          code-sign-certificate: ${{ secrets.P12_CER_BASE64 }}
              
          # The passphrase used to protect the code signing certificate. Pass this in
          # as a GitHub Encrypted Secret.
          code-sign-certificate-passphrase: ${{ secrets.P12_BASE64 }}
          
          # Identity to be used for code signing. If your project specifies a
          # `CODE_SIGN_IDENTITY`, this will override it.
          code-sign-identity: iOS Developer
          
          # A multiline list of Base64-encoded mobile provisioning profiles.
          mobile-provisioning-profiles-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          
          # A multiline list of Base64-encoded Mac provisioning profiles.
          provisioning-profiles-base64: ""
          
          # working-directory
          working-directory: ""
          
          # Typically `Release` or `Debug`.
          # Leave unset and `xcodebuild` decides itself.
          configuration: Debug
          
          # A scheme defined by an Xcode project or workspace.
          # If not specified, xcodebuild builds only the first target.
          scheme: MainApp
              
          # We try to detect your workspace, but if we fail you can manually specify
          # it with this parameter.
          workspace: ""
          
          # Fails the build if any warnings in *non test targets*.
          warnings-as-errors: false
          
          # One of `xcpretty`, `quiet` or `verbose`.
          verbosity: xcpretty
               
          # One of `always` or `on-failure`.
          # Consider `always` if you want access to your coverage-reports.
          # Beware that artifacts count against your GitHub Actions storage limits.
          upload-logs: on-failure         
      - name: ShowIpa
        run: |
          ls

      - name: Export
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: MainApp.xcodeproj
          scheme: MainApp
          p12-key-base64: ${{ secrets.P12_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          #mobileprovision-path: MainApp/embedded.mobileprovision
          code-signing-identity: iOS Developer
          certificate-password: ${{ secrets.PD }}
          team-id: ${{ secrets.TEAM_ID }}
          export-method: development
          configuration: Debug
          output-path: output/MainApp.ipa
      - name: ShowIpa
        run: |
          cd output; ls
