name: iOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: xcode
    runs-on: macos-latest
    steps:
      - name: Intstall
        run: brew install fastlane
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        uses: mxcl/xcodebuild@v1
        with:
          # A semantic version range, eg. ^10, ~10.3 or 10.3.1
          # Leave unset for the image‑default.
          xcode: 14.0
          swift: 5.5
          
          # Either `iOS`, `tvOS`, `macOS`, `watchOS` or (more rarely)  `mac-catalyst`
          # Leave unset and `xcodebuild` decides itself.
          platform: iOS
          
          # The most common actions are `test`, `build`.
          # See the `xcodebuild` manual for available actions.
          # Specifying `none` skips the explicit `xcodebuild` step allowing you
          # to use this (GitHub) Action solely for selecting an Xcode version.
          # Specifying `''`, `null` or `~` will cause xcodebuild to behave as it
          # does without an action specified (usually `build`)
          action: test         
          
          # Enables code coverage
          code-coverage: false
                    
          # Typically `Release` or `Debug`.
          # Leave unset and `xcodebuild` decides itself.
          configuration: Debug
          
          # A scheme defined by an Xcode project or workspace.
          # If not specified, xcodebuild builds only the first target.
          scheme: MainApp
              
          # We try to detect your workspace, but if we fail you can manually specify
          # it with this parameter.
          workspace: ""

          # Fails the build if any warnings in *non test targets*.
          warnings-as-errors: false
               
          # One of `always` or `on-failure`.
          # Consider `always` if you want access to your coverage-reports.
          # Beware that artifacts count against your GitHub Actions storage limits.
          upload-logs: on-failure  
      
      - name: Export
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: MainApp.xcodeproj
          scheme: MainApp
          p12-key-base64: ${{ secrets.P12_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          #mobileprovision-path: MainApp/embedded.mobileprovision
          code-signing-identity: iOS Developer
          certificate-password: ${{ secrets.PD }}
          team-id: ${{ secrets.TEAM_ID }}
          export-method: development
          configuration: Debug
          output-path: output/MainApp.ipa
      - name: ShowIpa
        run: |
          cd output; ls
