name: iOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        uses: mxcl/xcodebuild@v1
        with:
          xcode: 14.0
            description: |
              A semantic version range, eg. ^10, ~10.3 or 10.3.1
              Leave unset for the image‑default.
          swift: 5.5
             description: |
                A semantic version range, eg. ^5, ~5.4 or 5.4.1
          platform: iOS
             description: |
                Either `iOS`, `tvOS`, `macOS`, `watchOS` or (more rarely)
                `mac-catalyst`
                Leave unset and `xcodebuild` decides itself.
         action: test
            description: |
                * The most common actions are `test`, `build`.
                * See the `xcodebuild` manual for available actions.
                * Specifying `none` skips the explicit `xcodebuild` step allowing you
                to use this (GitHub) Action solely for selecting an Xcode version.
                * Specifying `''`, `null` or `~` will cause xcodebuild to behave as it
                does without an action specified (usually `build`)
         code-coverage: false
            description: |
                 Enables code coverage
         authentication-key-base64: ""
            description: |
              A Base64-encoded authentication key issued by App Store Connect. If
              specified, `xcodebuild`` will authenticate with the Apple Developer
              website using this credential. The `authentication-key-id` and
              `authentication-key-issuer-id` parameters are required. Using this key,
              `xcodebuild` will register the GitHub Actions runner device and manage
              code signing certificates for it. Please note that this may cause
              undesired behavior when using GitHub-hosted runners. For best results, use
              App Store Connect API keys only on self-hosted runners.
          authentication-key-id: ""
            description: |
              The key identifier associated with the App Store Conect authentication key
              specified in `authentication-key-base64`. This string can be located in
              the users and access details for your provider at
              "https://appstoreconnect.apple.com". For best results, use App Store
              Connect API keys only on self-hosted runners.
          authentication-key-issuer-id: ""
            description: |
              The App Store Connect issuer identifier associated with the authentication
              key specified in `authentication-key-base64`. This string can be located
              in the users and access details for your provider at
              "https://appstoreconnect.apple.com". For best results, use App Store
              Connect API keys only on self-hosted runners.
          code-sign-certificate: ""
            description: |
              A Base64-encoded certificate to be installed to the macOS Keychain for
              code signing. It is removed from the keychain in the post action. This
              certificate should correspond to the `CODE_SIGN_IDENTITY` specified in
              your project or to the `code-sign-identity` input. Pass this in as a
              GitHub Encrypted Secret. Requires macOS and
              `code-sign-certificate-passphrase`.
          code-sign-certificate-passphrase: ""
            description: |
              The passphrase used to protect the code signing certificate. Pass this in
              as a GitHub Encrypted Secret.
          code-sign-identity: ""
            description: |
              Identity to be used for code signing. If your project specifies a
              `CODE_SIGN_IDENTITY`, this will override it.
          mobile-provisioning-profiles-base64: ""
            description: |
              A multiline list of Base64-encoded mobile provisioning profiles.
          provisioning-profiles-base64: ""
            description: |
              A multiline list of Base64-encoded Mac provisioning profiles.
          working-directory: ""
            description: '…'
          configuration: Debug
            description: |
              Typically `Release` or `Debug`.
              Leave unset and `xcodebuild` decides itself.
          scheme: MainApp
            description: |
              A scheme defined by an Xcode project or workspace.
              If not specified, xcodebuild builds only the first target.
          workspace: ""
            description: |
              We try to detect your workspace, but if we fail you can manually specify
              it with this parameter.
          warnings-as-errors: false
            description: Fails the build if any warnings in *non test targets*.
          verbosity: xcpretty
            description: |
                One of `xcpretty`, `quiet` or `verbose`.
          upload-logs: on-failure
            description: |
              One of `always` or `on-failure`.
              Consider `always` if you want access to your coverage-reports.
              Beware that artifacts count against your GitHub Actions storage limits.
