name: Test Schedule
on:
  schedule:
     - cron: 15 * * * 1,5
# on:
#   push:
#     branches: [ "master" ]

jobs:
  test_mySchedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo time
        run: echo $(date)
