name: Test Schedule
on:
  schedule:
    - cron: '*/10 * * *'
    - cron: '10 6 * * *'
#      - cron: '5 * * * *'
#     - cron: '52 5 * * *'
     
# on:
#   push:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo time
        run: echo $(date)
      - name: Checkout
        uses: actions/checkout@v3
        
