name: Test Schedule
on:
  schedule:
     - cron: '5 * * * 1,5'
# on:
#   push:
#     branches: [ "master" ]

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo time
        run: echo $(date)
